name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate HTML
        run: |
          echo "Validando arquivos HTML..."
          for f in *.html; do
            tidy -qe "$f" || true
          done

      - name: Validate CSS
        run: |
          echo "Validando CSS..."
          npm install -g stylelint
          stylelint "**/*.css" || true

      - name: Validate JS
        run: |
          echo "Validando JS..."
          npm install -g eslint
          eslint "**/*.js" || true
